spellchecker: aspell

matrix:
- name: restructedtext
  sources:
  - ./**/*.rst
  hunspell:
    d: docs/spelling_wordlist.txt
  aspell:
    lang: en
  dictionary:
    wordlists:
    - docs/spelling_wordlist.txt
    output: build/dictionary/restructured.dic
  pipeline:
  - resplendent.filters.restructuredtext:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
  - pyspelling.filters.url:

- name: markdown
  sources:
  - ./**/*.md
  hunspell:
    d: docs/spelling_wordlist.txt
  aspell:
    lang: en
  dictionary:
    wordlists:
    - docs/spelling_wordlist.txt
    output: build/dictionary/mkdocs.dic
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
  - pyspelling.filters.url:

- name: python
  sources:
  - ./**/*.py
  hunspell:
    d: docs/src/dictionary/hunspell/en_AU
  aspell:
    lang: en
  dictionary:
    wordlists:
    - docs/spelling_wordlist.txt
    output: build/dictionary/python.dic
  pipeline:
  - pyspelling.filters.python:
      group_comments: true
  - pyspelling.flow_control.wildcard:
      allow:
      - py-comment
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore lint (noqa) and coverage (pragma) as well as shebang (#!)
      - open: '^(?: *(?:noqa\b|pragma: no cover)|!)'
        close: '$'
      # Ignore Python encoding string -*- encoding stuff -*-
      - open: '^ *-\*-'
        close: '-\*-$'
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: '\\[\\`]'
      delimiters:
      # Ignore multiline content between fences (fences can have 3 or more back ticks)
      # ```
      # content
      # ```
      - open: '(?s)^(?P<open> *`{3,})$'
        close: '^(?P=open)$'
      # Ignore text between inline back ticks
      - open: '(?P<open>`+)'
        close: '(?P=open)'
  - pyspelling.filters.url:
